version: '2'

services:
    micro_mysql:
        container_name: micro_mysql
        image: mysql:5.7
        ports:
            - 5000:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    micro_api:
        container_name: micro_api 
        image: denzdacs/react-laravel5.5-env:latest 
        ports:
            - 8011:80
        volumes:
            - ./api:/var/www/site
        working_dir: /var/www/site
        depends_on:
            - micro_mysql 
        restart: always
        working_dir: /var/www/site
    micro_vue:
        container_name: micro_vue  
        image: node:latest
        volumes:
            - ./view:/site
        command: > 
            bash -c "npm run serve"
        ports:
            - 3000:8080
        restart: always  
        depends_on:
            - micro_api 
        working_dir: /site
volumes:
    mysql-data:
